### PR TITLE
Sao/apigatewayv2

### PR DESCRIPTION
**Pull request by SorenOlegnowicz**

### CODE REVIEW

**Comment by SorenOlegnowicz** [comment]
FYI, in the partials that do not have tags, I have put the required properties at the bottom, so that there aren't any trailing commas in the blueprints.

**Review by rnhurt — CHANGES_REQUESTED** [review]
This looks good except for one thing; I would suggest that you sanitize the reference names: "apiv2{{this.name}}" should be "apiv2{{sanitize this.name ''}}".  

This has bitten me in the butt multiple times.  The problem is that some (most?) references (ie. {"Ref": "apiv2{{this.name}}"} ) don't like things like spaces and dashes.  Sanitizing them is the best way forward and just makes it easier in the future.

BTW: putting "static" arguments at the bottom is exactly what I do when there are no tags.  I wish JSON would allow trailing commas!!!!

**Comment by SorenOlegnowicz** [comment]
Ah, I did not realize that sanitize kept me from making that naming mistake I've kept making. Thank you!

Also, I bet someone important said "We can't have trailing commas, that would make JSON difficult to read!"

**Review by rnhurt — CHANGES_REQUESTED** [review]
You are close on the sanitize format, but not quite.  You have to give it the replacement character.  I just use nothing: ''

Change:  `{{sanitize this.Name}}` ---> `{{sanitize this.Name ''}}`

**Review by rnhurt — APPROVED** [review]
lgtm

**Pull request merged**
